import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.className}  antialiased bg-gradient-to-tr from-[#061b0a] from-40% via-[#003f0d] via-50% to-[#061b0a] to-70%`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
